env:
    browser: true
    es2021: true
    node: true
extends:
    - plugin:react/recommended
    - plugin:react-hooks/recommended
    - airbnb
    - airbnb-typescript
    - prettier
    - plugin:storybook/recommended
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: latest
    project: ./tsconfig.json
plugins:
    - react
    - react-hooks
    - '@typescript-eslint'
    - jest
    - jest-dom
    - testing-library
ignorePatterns:
    - vite.config.*
overrides:
    - files:
          - '**/__tests__/**/*.[jt]s?(x)'
          - '**/?(*.)+(spec|test).[jt]s?(x)'
      extends:
          - plugin:jest/recommended
          - plugin:jest-dom/recommended
          - plugin:testing-library/react
rules:
    {
        import/named: error,
        import/prefer-default-export: off,
        class-methods-use-this: off,
        react/react-in-jsx-scope: off,
        react/jsx-boolean-value: error,
        react/jsx-curly-brace-presence: error,
        react/jsx-props-no-spreading: off,
        react/function-component-definition: [2, { namedComponents: 'arrow-function' }],
        react/self-closing-comp: ['error', { component: true, html: true }],
        react-hooks/rules-of-hooks: error,
        react-hooks/exhaustive-deps: warn,
    }
