extends:
    - stylelint-config-standard-scss
    - stylelint-config-recess-order
    - stylelint-prettier/recommended
    - stylelint-config-prettier
plugins:
    - stylelint-scss
    - stylelint-prettier
processors:
    - - stylelint-processor-styled-components
      - ignoreFiles:
            - '**/*.css'
            - '**/*.scss'
rules: { 'at-rule-no-unknown': null, 'scss/at-rule-no-unknown': true, no-empty-source: null }
