name: Build and test

on:
    pull_request:
    pull_request_target:
        types:
            - opened

jobs:
    build-and-test:
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.platform }}
        if: (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') || (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
        steps:
            - name: checkout PR branch
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: install Rust stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
            - name: install app dependencies and build it
              run: npm install && npm run tauri build
            - name: frontend test
              run: npm install && npm run test
            - name: backend test
              run: cd src-tauri && cargo test
            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    build-storybook:
        runs-on: ubuntu-latest
        steps:
            - name: checkout PR branch
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: install node package dependencies and build it
              run: npm install && npm run build-storybook
