name: Pull Request check

on:
    pull_request_target:
        types: [opened]

    workflow_dispatch:

jobs:
    build-app:
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-latest, windows-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - name: Checkout current branch
                uses: actions/checkout@v2
                with:
                ref: ${{ github.event.pull_request.head.sha }}
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: install Rust stable
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
            - name: install app dependencies and build it
              run: npm install && npm run tauri build
            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    build-storybook:
        platform: ubuntu-latest
        steps:
            - name: Checkout current branch
                uses: actions/checkout@v2
                with:
                ref: ${{ github.event.pull_request.head.sha }}
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: install node package dependencies and build it
              run: npm install && npm run build-storybook
    test:
        platform: ubuntu-latest
        steps:
            - name: Checkout current branch
                uses: actions/checkout@v2
                with:
                ref: ${{ github.event.pull_request.head.sha }}
            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: install node package dependencies and test it
              run: npm install && npm run test
